#!/bin/sh
 
APP="python /goagent/proxy.py"
PID_FILE="/var/run/goagent.pid"
 
startGoa() {
		echo "start"
        #start-stop-daemon -S -x $APP -p $PID_FILE -m -b
}
 
stopGoa() {
		echo "stop"
        #start-stop-daemon -K -p $PID_FILE -s TERM
        #rm -rf $PID_FILE
}

case "$1" in
  start)
    startGoa
    ;;
  stop)
	stopGoa
    ;;
  *)
    startGoa
    ;;
esac

exit 0